version: "3.7"

services:


  crudtest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 80 on the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=CustomerDb;Username=admin;Password=password
    depends_on:
      - postgres  # Ensure the database starts before your application
    networks: 
      - backend



  # -----------------------------
  # postgres database
  # -----------------------------
  postgres:
    hostname: postgres
    image: postgres:13.3
    restart: unless-stopped
    volumes: 
      - psql-micro:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: CustomerDb
        
    ports:
      - 5432:5432
    networks: 
      - backend


# -----------------------------
# networks
# -----------------------------
networks:
  backend: 
    driver: bridge

# -----------------------------
# volumes
# -----------------------------
volumes: 
  psql-micro:
    driver: local
